# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=17
# Mod properties
mod.aw_version=1.21.1
mod.at_version=1.21.1
mod.fabric_range==1.20.1
mod.neoforge_range=DONOTUSE
# Dependency versions
deps.minecraft=1.20.1
deps.parchment=2023.09.03
deps.fabric-loader=0.19.2
deps.fabric-api=0.92.9
deps.neoforge=DONOTUSE
deps.modmenu=9.0.0
# cloth config 15.0.140 crash when saving config
deps.cloth_config=14.0.125
