# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.configuration-cache=false
org.gradle.parallel=true
org.gradle.caching=true
# Java
java.version=[JAVA_VERSION_VERSIONED]
# Mod properties
mod.id=musicnotification
mod.name=MusicNotification
mod.version=3.2.1
mod.group=net.kosmo
mod.license=LGPL-3.0-only
mod.description=Add notifications when music is played in the game with info about the track being played. And play music any time you want.
mod.github=https://github.com/KosmoMoustache/MusicNotification
mod.aw_version=[MOD_AW_VERSION_VERSIONED]
mod.at_version=[MOD_AT_VERSION_VERSIONED]
mod.fabric_range=[MOD_FABRIC_RANGE_VERSIONED]
mod.neoforge_range=[MOD_NEOFORGE_RANGE_VERSIONED]
# Dependency versions
deps.minecraft=[DEPS_MINECRAFT_VERSIONED]
deps.parchment=[DEPS_PARCHMENT_VERSIONED]
deps.fabric-loader=[DEPS_FABRIC_LOADER_VERSIONED]
deps.fabric-api=[DEPS_FABRIC_API_VERSIONED]
deps.neoforge=[DEPS_NEOFORGE_VERSIONED]
deps.modmenu=[DEPS_MODMENU_VERSIONED]
deps.cloth_config=[DEPS_CLOTH_CONFIG_VERSIONED]
# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
stonecutter_enabled_common_versions=1.21.1, 1.21.4, 1.21.7, 1.21.8, 1.21.10, 1.21.11, 26.1, 26.2
#stonecutter_enabled_common_versions=26.2
stonecutter_enabled_fabric_versions=1.21.1, 1.21.4, 1.21.7, 1.21.8, 1.21.10, 1.21.11, 26.1, 26.2
#stonecutter_enabled_fabric_versions=26.2
stonecutter_enabled_neoforge_versions=1.21.1, 1.21.4, 1.21.7, 1.21.8, 1.21.10, 1.21.11, 26.1, 26.2
#stonecutter_enabled_neoforge_versions=26.2
# loom-back-compat
loomx.loom_version=1.16-SNAPSHOT



