# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=true
# Java
java.version=[VERSIONED]
# Mod properties
mod.name=MusicNotification
mod.id=musicnotification
mod.group=net.kosmo
mod.version=3.0.0
mod.license=LGPL-3.0-only
mod.author=KosmoMoustache
mod.description=Add notifications when music is played in the game with info about the track being played. And play music any time you want.
mod.github=https://github.com/KosmoMoustache/MusicNotification
# Minecraft
minecraft_version=[VERSIONED]
min_minecraft_version=[VERSIONED]
aw_version=[VERSIONED]
# Mappings
deps.parchment=[VERSIONED]
# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
stonecutter_enabled_common_versions=1.21.7, 1.21.8, 1.21.10
stonecutter_enabled_fabric_versions=1.21.7, 1.21.8, 1.21.10
stonecutter_enabled_neoforge_versions=1.21.7, 1.21.8, 1.21.10
# Fabric https://fabricmc.net/develop/
deps.fabric-loader=[VERSIONED]
deps.fabric-api=[VERSIONED]
# NeoForge https://projects.neoforged.net/neoforged/neoforge
deps.neoforge=[VERSIONED]
# Dependencies
deps.modmenu=[VERSIONED]
deps.clothConfig=[VERSIONED]