# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=25
# Minecraft
minecraft_version=26.1
min_minecraft_version=26.1
aw_version=1.21.7
# Mappings
deps.parchment=
# Fabric
deps.fabric-loader=0.18.4
deps.fabric-api=0.144.1
# NeoForge
deps.neoforge=26.1.0.1-beta
# Dependencies
deps.modmenu=18.0.0-alpha.7
deps.cloth_config=26.1.154

mod.aw=1.21.7-unobf
mod.releases=
mod.compat=[26.1]
deps.minecraft=26.1