# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=25
# Mod properties
mod.aw=1.21.7-unobf
mod.fabric_range=~26.1
mod.neoforge_range=[26.1,26.2)
# Dependency versions
deps.minecraft=26.1
deps.parchment=
deps.fabric-loader=0.18.4
deps.fabric-api=0.144.3
deps.neoforge=26.1.0.1-beta
deps.modmenu=18.0.0-alpha.7
deps.cloth_config=26.1.154


