# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=21
# Mod properties
mod.aw_version=1.21.7
mod.at_version=1.21.7
mod.fabric_range==1.21.11
mod.neoforge_range=[1.21.11]
# Dependency versions
deps.minecraft=1.21.11
deps.parchment=2025.12.20
deps.fabric-loader=0.19.2
deps.fabric-api=0.141.3
deps.neoforge=21.11.42
deps.modmenu=17.0.0
deps.cloth_config=21.11.153