# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=25
# Mod properties
mod.aw_version=26.1-unobf
mod.at_version=26.1-unobf
mod.fabric_range=~26.2
mod.neoforge_range=[26.2,26.3)
# Dependency versions
deps.minecraft=26.2
deps.parchment=
deps.fabric-loader=0.19.3
deps.fabric-api=0.154.2
deps.neoforge=26.2.0.18-beta
deps.modmenu=20.0.1
deps.cloth_config=26.2.155


