# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=21
# Mod properties
mod.aw_version=1.21.7
mod.at_version=1.21.7
mod.fabric_range==1.21.10
mod.neoforge_range=[1.21.10]
# Dependency versions
deps.minecraft=1.21.10
deps.parchment=2025.10.12
deps.fabric-loader=0.19.2
deps.fabric-api=0.138.4
deps.neoforge=21.10.64
deps.modmenu=16.0.1
deps.cloth_config=20.0.149
