# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=21
# Mod properties
mod.aw_version=1.21.4
mod.at_version=1.21.4
mod.fabric_range==1.21.8
mod.neoforge_range=[1.21.8]
# Dependency versions
deps.minecraft=1.21.8
deps.parchment=2025.09.14
deps.fabric-loader=0.19.2
deps.fabric-api=0.136.1
deps.neoforge=21.8.53
deps.modmenu=15.0.2
deps.cloth_config=19.0.147
