# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=21
# Mod properties
mod.aw=1.21.7
mod.fabric_range==1.21.7
mod.neoforge_range=[1.21.7]
# Dependency versions
deps.minecraft=1.21.7
deps.parchment=2025.07.18
deps.fabric-loader=0.18.4
deps.fabric-api=0.129.0
deps.neoforge=21.7.25-beta
deps.modmenu=15.0.1
deps.cloth_config=19.0.147
