modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_github}/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "KosmoMoustache"
description = "${mod_description}"
logoFile = "icon.png"
logoBlur = false

credits = """
Thanks to:
    Authors:
        KosmoMoustache
    Contributors:
        carotteatomique
        akairoo
        Totchi Lagawi
    Translators:
        Chiloven945
"""

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}-common.mixins.json"

[[dependencies.$mod_id]]
modId = "neoforge"
type = "required"
versionRange = "[$neoforge,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.$mod_id]]
modId = "minecraft"
type = "required"
versionRange = "$neoforge_mc_range"
ordering = "NONE"
side = "BOTH"

[[dependencies.$mod_id]]
modId = "cloth_config"
type = "required"
versionRange = "[$cloth_config,)"
ordering = "NONE"
side = "CLIENT"



