modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${modGitHub}/issues"
license = "${modLicense}"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.png"
logoBlur = false

credits = """
Thanks to:
    Authors:
        KosmoMoustache
    Contributors:
        carotteatomique
        akairoo
        Totchi Lagawi
    Translators:
        Chiloven945
"""

[[mixins]]
config = "${modId}.mixins.json"

[[mixins]]
config = "${modId}-common.mixins.json"

[[dependencies.${ modId }]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "minecraft"
type = "required"
versionRange = "[${minMinecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "cloth_config"
type = "required"
versionRange = "[${clothConfigVersion},)"
ordering = "NONE"
side = "CLIENT"



