# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=25
# Mod properties
mod.aw_version=26.1-unobf
mod.at_version=26.1-unobf
mod.fabric_range=~26.3
mod.neoforge_range=[26.3,26.4)
# Dependency versions
deps.minecraft=26.3
deps.parchment=
deps.fabric-loader=0.19.5
deps.fabric-api=0.160.5
deps.neoforge=26.3.0.1-beta
deps.modmenu=21.0.0-beta.1
deps.cloth_config=26.3.158
