# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=21
# Mod properties
mod.aw_version=1.21.1
mod.at_version=1.21.1
mod.fabric_range==1.21.1
mod.neoforge_range=[1.21.1]
# Dependency versions
deps.minecraft=1.21.1
deps.parchment=2024.11.17
deps.fabric-loader=0.19.2
deps.fabric-api=0.116.11
deps.neoforge=21.1.228
deps.modmenu=11.0.4
# cloth config 15.0.140 crash when saving config
deps.cloth_config=15.0.130
