# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
# Java
java.version=21
# Minecraft
minecraft_version=1.21.1
min_minecraft_version=1.21.1
aw_version=1.21.1
# Mappings
deps.parchment=2024.11.17
# Fabric
deps.fabric-loader=0.18.4
deps.fabric-api=0.116.9
# NeoForge
deps.neoforge=21.1.220
# Dependencies
deps.modmenu=11.0.1
# cloth config 15.0.140 crash when saving config
deps.cloth_config=15.0.130

mod.aw=1.21.1
mod.releases=1.21.1
mod.compat=[1.21.1]
deps.minecraft=1.21.1